server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: housekeep-backend
  profiles:
    active: dev
  # 文件上传配置 开放更大的文件上传体积
  servlet:
    multipart:
      max-file-size: 10MB
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/housekeep?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123
  redis:
    host: localhost
    port: 6379
    database: 0
  cache:
    redis:
      time-to-live: 1800000 #设置缓存数据的过期时间




mybatis-plus:
  configuration:
    # 开启驼峰命名自动映射 (数据库 is_deleted -> 实体类 isDeleted)
    map-underscore-to-camel-case: true
    # 开发环境打印 SQL 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 全局主键类型: assign_id (雪花算法)，完美契合我们的 BIGINT 主键
      id-type: assign_id
      # 逻辑删除配置
      logic-delete-field: isDeleted # 注意：这里填的是 Java 实体类中的字段名，而不是数据库列名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值

# 图片存储方式配置 (local: 本地存储, oss: 阿里云OSS)
storage:
  type: local
  local-base-path: D:/img/uploads
  local-access-url: http://localhost:8081/api/uploads
  enable-compress: true
  max-width: 1920
  compress-quality: 0.75
  compress-threshold: 204800

#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-study-ai-start
    region: cn-beijing


knife4j:
  enable: true
  openapi:
    title: 官方文档
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.itxc.housekeepbackend.controller


